### ISSUE TITLE
Support for XState v5

### ISSUE THREAD

**Issue by ovidb** [cpetzel/react-native-flipper-xstate#5]
First and foremost I would like to state how useful your plugin is as. I can not imagine not using it. 

However it doesn't work with XState v5 which has now been officially released. We are planning to migrate to V5 but believe it or not we believe in spite of all the good features of v5, loosing the DX provided by your plugin is too big of a loss, so I would like to ask you if you plan to update your plugin to support v5?

Again, thank you very much for this plugin.

**Comment by cpetzel** [comment]
Thank you for the kind words, I am glad you find it useful! 

I took a peak at supporting V5, but it looks like the official Xstate/inspect package has not been officially released... [Their package.json still has 0.8.0, which was last updated 8 months ago. ](https://github.com/statelyai/xstate/blob/main/packages/xstate-inspect/package.json#L3)

[Also, their official V5 documentation does not contain anything on the inspector yet](https://stately.ai/docs/inspector), but does [mention that the visualizer is coming](https://stately.ai/blog/2023-12-01-xstate-v5#inspect-api). 

I can try and pull down their code and see if I can get it to work with an unofficial release, but it might be a bit longer until I can officially update this.

**Comment by davidkpiano** [comment]
Hey @cpetzel! We (silently) released the new inspect API that supports XState v5 here: https://github.com/statelyai/inspect

We're making a couple fixes and will be making a bigger announcement this week.

**Comment by caseygibson-emesent** [comment]
@cpetzel is this something you're currently looking into now that the new inspect API has been released or will it be some time before you have a chance to look at it?

**Comment by cpetzel** [comment]
I have created a few new tools for inspecting v5 state machines! 

Since React Native has recently deprecated Flipper, I have created an Expo Dev Tool plugin for inspecting machines using Expo's browser based tooling system. I also created an in-app "floating inspector" that lets you view your machines inside of your application!

Give this a try and let me know if you have any questions or feedback!
https://github.com/cpetzel/expo-xstate-inspect
![devpluginactordemo](https://github.com/cpetzel/react-native-flipper-xstate/assets/2036206/8881e4ed-ea33-48c5-a17a-80f57ba76d1b)

![FloatingInspectDemo](https://github.com/cpetzel/react-native-flipper-xstate/assets/2036206/e1b45990-146a-483e-ae68-e0ae4b4eb286)

**Comment by CyberCyclone** [comment]
That looks awesome, nice work @cpetzel! 

Is there a reason it's a expo based plugin and not a react-native plugin?

**Comment by cpetzel** [comment]
Thanks!

As far as the web inspector goes, React Native (Metro) does not support developer plugins. [Expo created Developer plugins which sit on top of metro](https://docs.expo.dev/debugging/devtools-plugins/)

However, the floating inspector is NOT tied to expo. You can use that package in a regular react native project (with reanimated and RN Gesture Handler). I had created the expo plugin first when I first created this, and had not renamed the git repository.
